version: '4.41'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - authdb:/var/lib/postgresql/data

volumes:
  authdb:
